config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html
resources :salary_reports do
  get 'report'
end

app/models/salary_report.rb
class SalaryReport < ActiveRecord::Base

  WEEKS_PER_YEAR = 52.2

  belongs_to :user
  before_create :setup

  # Setup a report using the current settings.
  def setup
    self.week_hours = Setting.plugin_salary_reports[:week_hours]
    self.weeks_of_per_year = Setting.plugin_salary_reports[:weeks_of_per_year] 
    self.days_of_per_year = Setting.plugin_salary_reports[:days_of_per_year] 
    self.start_date = self.user.custom_field_values.select{|v| v.custom_field.name == "Employment Date"}.first.value
    self.workload = self.user.custom_field_values.select{|v| v.custom_field.name == "Workload"}.first.value.to_f * 0.01
    self.salary = Setting.plugin_salary_reports[:salary].to_f * self.workload
    self.ahv_rate = Setting.plugin_salary_reports[:ahv_rate].to_f * 0.01
    self.alv_rate = Setting.plugin_salary_reports[:alv_rate].to_f * 0.01
    self.pension_pool_rate = Setting.plugin_salary_reports[:pension_pool_rate].to_f * 0.01
    self.nbu_rate = Setting.plugin_salary_reports[:nbu_rate].to_f * 0.01
    self.nbu_rate_frac = Setting.plugin_salary_reports[:nbu_rate_frac].to_f
  end

  # Fraction of year considered in the report
  def frac(date_from)
    delay = (self.date_to - date_from) / 24 / 3600
    delay / 365 
  end

  # Calculate the total number of working hours per year.
  def working_hours_per_year
    WEEKS_PER_YEAR * self.week_hours
  end

  # Returns the date, when person started working or beginning of year.
  def employment_date
    if self.start_date.nil? or self.start_date < Date.today.at_beginning_of_year
      return Date.today.at_beginning_of_year.to_time
    else
      return self.start_date
    end
  end
  
  # Hours worked during period
  def working_hours(date_from = self.date_from)
    TimeEntry.where(user: self.user, spent_on: date_from..self.date_to).sum{|t| t.hours }
  end
  
  # Hours worked during period ignoring holidays and days of
  def working_hours_ignoring_holidays(date_from = self.date_from)
    TimeEntry.where(user: self.user, spent_on: date_from..self.date_to).sum{|t| !["Ferien", "Feiertag"].include?(t.activity.name)  ? t.hours : 0}
  end

  # AHV rate employee
  def ahv_rate_employee
    self.ahv_rate / 2
  end
  
  # AHV contributions
  def ahv_contribution  
    self.salary_net * self.ahv_rate_employee
  end

  # AHV rate employee
  def alv_rate_employee
    self.alv_rate / 2
  end
  
  # ALV contributions
  def alv_contribution  
    self.salary_net * self.alv_rate_employee
  end

  # Pension pool rate employee
  def pension_pool_rate_employee
    self.pension_pool_rate
  end
  
  # Pension pool contributions
  def pension_pool_contribution  
    self.salary_net * self.pension_pool_rate_employee
  end

  # Pension pool rate employee
  def nbu_rate_employee
    self.nbu_rate * self.nbu_rate_frac
  end
  
  # Pension pool contributions
  def nbu_contribution  
    self.salary_net * self.nbu_rate_employee
  end

  # Summarize all contributions
  def total_contributions
    self.ahv_contribution + self.alv_contribution + self.nbu_contribution + self.pension_pool_contribution
  end

  # Net salary 
  def salary_net
    self.salary
  end

  # Total salary (Gross)
  def salary_gross
    self.salary + self.total_contributions
  end

  def calc_overtime_ignoring_holidays(date_from = self.date_from)
    goalTot =  self.working_hours_per_year - (self.weeks_of_per_year * self.week_hours + self.days_of_per_year * self.week_hours / 5)
    goal = self.workload * goalTot * frac(date_from)
    self.working_hours_ignoring_holidays(date_from) - goal
  end
  
  def calc_overtime_considering_holidays(date_from = self.date_from)
    goalTot =  self.working_hours_per_year
    goal = self.workload * goalTot * frac(date_from)
    self.working_hours(date_from) - goal
  end
  
  def calc_holidays_taken(date_from = self.date_from)
    TimeEntry.where(user: self.user, spent_on: date_from..self.date_to).sum{|t| "Ferien" == t.activity.name ? t.hours : 0}
  end

  def calc_percentage_holidays_taken
    100 * (self.calc_holidays_taken / (self.weeks_of_per_year * self.week_hours * self.workload))
  end

end

app/controllers/salary_reports_controller.rb
class SalaryReportsController < ApplicationController
  before_action :set_salary_report, only: %i[ show edit update destroy ]


  # GET /salary_reports/:id/report
  def report
    @salary_report = SalaryReport.find(params[:salary_report_id])
    respond_to do |format|
      format.pdf {
        puts "*"*100
        puts "Rendering PDF"
        puts "*"*100
      }
    end
  end

  # GET /salary_reports or /salary_reports.json
  def index
    @salary_reports = SalaryReport.all.order(id: :asc)
  end

  # GET /salary_reports/:id
  def show
  end

  # GET /salary_reports/new
  def new
    @salary_report = SalaryReport.new
  end

  # GET /salary_reports/1/edit
  def edit
  end

  # POST /salary_reports or /salary_reports.json
  def create
    @salary_report = SalaryReport.new(salary_report_params)

    respond_to do |format|
      if @salary_report.save
        format.html { redirect_to salary_report_url(@salary_report), notice: "Report was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /salary_reports/1 or /salary_reports/1.json
  def update
    respond_to do |format|
      if @salary_report.update(salary_report_params)
        format.html { redirect_to salary_report_url(@salary_report), notice: "Report was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /salary_reports/1 or /salary_reports/1.json
  def destroy
    @salary_report.destroy

    respond_to do |format|
      format.html { redirect_to salary_reports_url, notice: "report was successfully destroyed." }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_salary_report
      @salary_report = SalaryReport.find(params[:id])
    end
    # Only allow a list of trusted parameters through.
    def salary_report_params
      params.require(:salary_report).permit(:date_from, :date_to, :user_id)
    end

end

app/helpers/salary_report_helper.rb
module SalaryReportHelper
end

app/views/salary_reports/_form.html.erb
<%= form_with(model: salary_report, data: {turbo: false}) do |form| %>


  <div>
    <%= form.label :date_from %>
    <%= form.date_field :date_from, value: Date.today.at_beginning_of_month if salary_report.new_record? %>
  </div>

  <div>
    <%= form.label :date_to %>
    <%= form.date_field :date_to, value: Date.today.at_end_of_month if salary_report.new_record? %>
  </div>

  <div>
    <%= form.label :user_id %>
    <%= form.collection_select(:user_id, User.all, :id, :login, {prompt: true, selected: (User.current if salary_report.new_record?)}) %>
  </div>

  <div>
    <%= form.submit %>
  </div>


<% end %>

app/views/salary_reports/index.html.erb
<% html_title t('.reports') %>
<h2><%= t('.reports_title') %></h2>

<%= link_to t(".new_report"), new_salary_report_path %>
<br>
<br>
<table>
  <tbody>
    <% @salary_reports.each do |salary_report| %>
      <tr>
        <td><%= link_to "#{I18n.l(salary_report.date_from, format: '%d. %B %Y')} - #{I18n.l(salary_report.date_to, format: '%d. %B %Y')}", salary_report %></td>
        <td><%= link_to salary_report.user, salary_report.user %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/salary_reports/new.html.erb
<% html_title t('.new_report') %>
<h1><%= t('.new_report') %></h1>

<%= render "form", salary_report: @salary_report %>

app/views/salary_reports/show.html.erb
<% html_title "#{t('.report')} #{I18n.l @salary_report.date_from, format: "%d.%m.%y"} - #{I18n.l @salary_report.date_to, format: "%d.%m.%y"}" %>
<h2><%= t('.report') %></h2>

<%= link_to t('.pdf'), "#{salary_report_report_path(@salary_report)}.pdf", target: :_blank %>

<p>
  <strong><%= t '.user' %></strong>: <%= link_to @salary_report.user, @salary_report.user %>
</p>
<p>
  <strong><%= t '.date_from' %></strong>: <%= I18n.l @salary_report.date_from, format: "%d. %B %Y" %>
</p>
<p>
  <strong><%= t '.date_to' %></strong>: <%= I18n.l @salary_report.date_to, format: "%d. %B %Y" %>
</p>

<hr>
<h3><%= t '.salary' %></h3>
<p>
  <strong><%= t '.salary_net' %></strong>: <%= "%0.2f" % @salary_report.salary_net %>Chf
</p>
<p>
  <strong><%= t '.ahv_contributions' %></strong>: <%= "%0.2f" % @salary_report.ahv_contribution %>Chf (<%= "%0.2f" % (@salary_report.ahv_rate_employee * 100) %>%)
</p>
<p>
  <strong><%= t '.alv_contributions' %></strong>: <%= "%0.2f" % @salary_report.alv_contribution %>Chf (<%= "%0.2f" % (@salary_report.alv_rate_employee * 100) %>%)
</p>
<p>
  <strong><%= t '.pension_pool_contributions' %></strong>: <%= "%0.2f" % @salary_report.pension_pool_contribution %>Chf (<%= "%0.2f" % (@salary_report.pension_pool_rate_employee * 100) %>%)
</p>
<p>
  <strong><%= t '.nbu_contributions' %></strong>: <%= "%0.2f" % @salary_report.nbu_contribution %>Chf (<%= "%0.2f" % (@salary_report.nbu_rate_employee * 100) %>%)
</p>
<p>
  <strong><%= t '.total_contributions' %></strong>: <%= "%0.2f" % @salary_report.total_contributions %>Chf
</p>
<p>
  <strong><%= t '.salary_gross' %></strong>: <%= "%0.2f" % @salary_report.salary_gross %>Chf
</p>

<hr>

<h3><%= t '.report_period' %></h3>
<p>
<strong><%= t '.working_hours' %></strong>: <%= "%0.2f" % @salary_report.working_hours %>h
</p>
<p>
<strong><%= t '.holidays' %></strong>: <%= "%0.2f" % @salary_report.calc_holidays_taken %>h
</p>
<p>
<strong><%= t '.working_hours_ignoring_holidays' %></strong>: <%= "%0.2f" % @salary_report.working_hours_ignoring_holidays %>h
</p>
<p>
<strong><%= t '.calc_overtime_ignoring_holidays' %></strong>: <%= "%0.2f" % @salary_report.calc_overtime_ignoring_holidays %>h
</p>
<p>
<strong><%= t '.calc_overtime_considering_holidays' %></strong>: <%= "%0.2f" % @salary_report.calc_overtime_considering_holidays %>h
</p>

<hr>

<h3><%= t '.current_year' %></h3>
<p>
  <strong><%= t '.since' %></strong>: <%= I18n.l @salary_report.employment_date, format: "%d. %B %Y" %>
</p>
<p>
<strong><%= t '.calc_overtime_ignoring_holidays_current_year' %></strong>: <%= "%0.2f" % @salary_report.calc_overtime_ignoring_holidays(@salary_report.employment_date) %>
</p>
<p>
<strong><%= t '.calc_overtime_considering_holidays_current_year' %></strong>: <%= "%0.2f" % @salary_report.calc_overtime_considering_holidays(@salary_report.employment_date) %>
</p>
<p>
<strong><%= t '.calc_holidays_taken_current_year' %></strong>: <%= "%0.2f" % @salary_report.calc_holidays_taken(@salary_report.employment_date) %>
</p>
<p>
<strong><%= t '.calc_percentage_holidays_taken_current_year' %></strong>: <%= "%0.2f" % @salary_report.calc_percentage_holidays_taken %>
</p>

<hr>

<h3><%= t '.report_setup' %></h3>
<p>
  <strong><%= t '.week_hours' %></strong>: <%= @salary_report.week_hours %>h
</p>
<p>
  <strong><%= t '.weeks_of_per_year' %></strong>: <%= @salary_report.weeks_of_per_year %>
</p>
<p>
  <strong><%= t '.days_of_per_year' %></strong>: <%= @salary_report.days_of_per_year %>
</p>
<p>
  <strong><%= t '.start_date' %></strong>: <%= I18n.l @salary_report.start_date, format: "%d. %B %Y" %>
</p>
<p>
  <strong><%= t '.workload' %></strong>: <%= @salary_report.workload * 100 %>%
</p>

<%= link_to t('.delete'), @salary_report, method: :delete, data: {confirm: t('.confirm')}%>